# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: object_detection/protos/region_similarity_calculator.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n:object_detection/protos/region_similarity_calculator.proto\x12\x17object_detection.protos\"\x85\x02\n\x1aRegionSimilarityCalculator\x12N\n\x16neg_sq_dist_similarity\x18\x01 \x01(\x0b\x32,.object_detection.protos.NegSqDistSimilarityH\x00\x12@\n\x0eiou_similarity\x18\x02 \x01(\x0b\x32&.object_detection.protos.IouSimilarityH\x00\x12@\n\x0eioa_similarity\x18\x03 \x01(\x0b\x32&.object_detection.protos.IoaSimilarityH\x00\x42\x13\n\x11region_similarity\"\x15\n\x13NegSqDistSimilarity\"\x0f\n\rIouSimilarity\"\x0f\n\rIoaSimilarity')



_REGIONSIMILARITYCALCULATOR = DESCRIPTOR.message_types_by_name['RegionSimilarityCalculator']
_NEGSQDISTSIMILARITY = DESCRIPTOR.message_types_by_name['NegSqDistSimilarity']
_IOUSIMILARITY = DESCRIPTOR.message_types_by_name['IouSimilarity']
_IOASIMILARITY = DESCRIPTOR.message_types_by_name['IoaSimilarity']
RegionSimilarityCalculator = _reflection.GeneratedProtocolMessageType('RegionSimilarityCalculator', (_message.Message,), {
  'DESCRIPTOR' : _REGIONSIMILARITYCALCULATOR,
  '__module__' : 'object_detection.protos.region_similarity_calculator_pb2'
  # @@protoc_insertion_point(class_scope:object_detection.protos.RegionSimilarityCalculator)
  })
_sym_db.RegisterMessage(RegionSimilarityCalculator)

NegSqDistSimilarity = _reflection.GeneratedProtocolMessageType('NegSqDistSimilarity', (_message.Message,), {
  'DESCRIPTOR' : _NEGSQDISTSIMILARITY,
  '__module__' : 'object_detection.protos.region_similarity_calculator_pb2'
  # @@protoc_insertion_point(class_scope:object_detection.protos.NegSqDistSimilarity)
  })
_sym_db.RegisterMessage(NegSqDistSimilarity)

IouSimilarity = _reflection.GeneratedProtocolMessageType('IouSimilarity', (_message.Message,), {
  'DESCRIPTOR' : _IOUSIMILARITY,
  '__module__' : 'object_detection.protos.region_similarity_calculator_pb2'
  # @@protoc_insertion_point(class_scope:object_detection.protos.IouSimilarity)
  })
_sym_db.RegisterMessage(IouSimilarity)

IoaSimilarity = _reflection.GeneratedProtocolMessageType('IoaSimilarity', (_message.Message,), {
  'DESCRIPTOR' : _IOASIMILARITY,
  '__module__' : 'object_detection.protos.region_similarity_calculator_pb2'
  # @@protoc_insertion_point(class_scope:object_detection.protos.IoaSimilarity)
  })
_sym_db.RegisterMessage(IoaSimilarity)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _REGIONSIMILARITYCALCULATOR._serialized_start=88
  _REGIONSIMILARITYCALCULATOR._serialized_end=349
  _NEGSQDISTSIMILARITY._serialized_start=351
  _NEGSQDISTSIMILARITY._serialized_end=372
  _IOUSIMILARITY._serialized_start=374
  _IOUSIMILARITY._serialized_end=389
  _IOASIMILARITY._serialized_start=391
  _IOASIMILARITY._serialized_end=406
# @@protoc_insertion_point(module_scope)
